name: GitHub Output
on:
  issues:
    types: opened
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output event details
              run: echo "${{toJson(github.event)}}"
